// src/lib/seedAccidents.ts
import type { AccidentRecord } from '@/types'

export const ACCIDENT_RECORDS: AccidentRecord[] = [
  {
    id: 'acc-001',
    name: 'สมชาย ใจดี',
    department: 'PR',
    accidentDate: '2026-01-15',
    daysOff: 5,
    injuryLevel: 'หยุดงานเกิน 3 วัน',
    causeAgent: 'พื้นลื่น/ขรุขระ',
    injuryNature: 'ล้ม/พลัดตก',
    bodyPart: 'ข้อเท้า/เท้า',
    cause: 'Unsafe Con.',
    expenses: 3500,
    useCompFund: true,
    year: 2026,
    details: 'ลื่นล้มบริเวณพื้นห้องผลิต ข้อเท้าพลิก',
  },
  {
    id: 'acc-002',
    name: 'วิภา รักงาน',
    department: 'MC',
    accidentDate: '2026-02-20',
    daysOff: 1,
    injuryLevel: 'หยุดงานไม่เกิน 3 วัน',
    causeAgent: 'เครื่องจักร/อุปกรณ์',
    injuryNature: 'ถูกของหนีบ/บีบ',
    bodyPart: 'มือ/นิ้วมือ',
    cause: 'Unsafe Act.',
    expenses: 800,
    useCompFund: false,
    year: 2026,
    details: 'นิ้วถูกหนีบขณะซ่อมบำรุงเครื่องจักร',
  },
  {
    id: 'acc-003',
    name: 'ประสิทธิ์ มีสุข',
    department: 'ST',
    accidentDate: '2026-03-08',
    daysOff: 0,
    injuryLevel: 'ไม่หยุดงาน',
    causeAgent: 'วัตถุมีคม',
    injuryNature: 'ถูกของมีคมบาด/แทง',
    bodyPart: 'มือ/นิ้วมือ',
    cause: 'Unsafe Act.',
    expenses: 200,
    useCompFund: false,
    year: 2026,
    details: 'ถูกขอบกล่องกระดาษบาดบริเวณนิ้วมือ',
  },
]
